### ISSUE TITLE
Does fitmand have fitting problems?

### ISSUE THREAD

**Issue by piklprado** [piklprado/sads#11]
Check if fitting problems for Pareto distribution can occur (see pareto help page in VGAM:
(http://finzi.psych.upenn.edu/R/library/VGAM/html/pareto1.html) and also references in McGill's chapter on sads in Magurran & McGill (2011).

**Comment by andrechalom** [comment]
The link referenced is dead, but the current VGAM help pages displays the following warning:

     The usual or unbounded Pareto distribution has two parameters
     (called alpha and k here) but the family function ‘paretoff’
     estimates only k using iteratively reweighted least squares. The
     MLE of the alpha parameter lies on the boundary and is ‘min(y)’
     where ‘y’ is the response. Consequently, using the default
     argument values, the standard errors are incorrect when one does a
     ‘summary’ on the fitted object. If the user inputs a value for
     ‘alpha’ then it is assumed known with this value and then
     ‘summary’ on the fitted object should be correct. Numerical
     problems may occur for small k, e.g., k < 1.

**Comment by andrechalom** [comment]
OK, so if I understand this issue, the problem is related to the fixed parameters and how standard errors are calculated. If so, fitmand (and related distributions) do not have problems, as parameters declared as "fixed" in mle2 are not accounted for in `stdEr` estimations:
```R
> m <- fitmand(bci)
> coef(m)
         N          s          v 
225.000000   2.006446  15.048024 
> stdEr(m)
         s          v 
0.04009631 0.78027934 
```

**Comment by andrechalom** [comment]
Okay, I read the McGill chapter :)

We need to discuss this for all of the power functions (zipf, mand, maybe powbend), as apparently they are really hard to fit.

**Comment by piklprado** [comment]
Apparently these are general fitting problems, not a bug in our function.
