### ISSUE TITLE
Fixed parameters in logseries and zero-sum multinomial

### ISSUE THREAD

**Issue by piklprado** [piklprado/sads#12]
Check if parameters J for mszm and volkov and N for ls can be declared as fixed in their fitting functions.  This will also allow to eliminate a bunch of if's in radpred and octavpred.

**Comment by andrechalom** [comment]
Is this analogous in the parameters S/N for the zipf, mand and gs for the rad fitting?

**Comment by andrechalom** [comment]
Branch https://github.com/andrechalom/sads/tree/Fix12 implements this changes for ls, mzsm, volkov, zipf, mand and gs. It also cuts all the if's() in the octavpred, radpred, pprad and ppsad methods, which I find a great improvement.

As this branch is based on Fix13, it can be merged as soon as Fix13 is merged.
