### ISSUE TITLE
More informative call in fitting functions

### ISSUE THREAD

**Issue by piklprado** [piklprado/sads#13]
Use do.call to call mle2inside fitting functions to get the explicit arguments in the call slot and thus in the summary. This is done in fitvolkov, compare to e.g. fitls:

```r
> mag5 <- c(103,115,13,2,67,36,51,8,6,61,10,21,
+           7,65,4,49,92,37,16,6,23,9,2,6,5,4,
+           1,3,1,9,2)
> fitsad(mag5, "volkov",skip.hessian=TRUE)

Call:
mle2(minuslogl = function (theta, m) 
-sum(dvolkov(x, theta = theta, m = m, J = sum(x), log = TRUE)), 
    start = list(theta = 30.9999356649761, m = 0.5), method = "L-BFGS-B", 
    data = list(x = c(103, 115, 13, 2, 67, 36, 51, 8, 6, 61, 
    10, 21, 7, 65, 4, 49, 92, 37, 16, 6, 23, 9, 2, 6, 5, 4, 1, 
    3, 1, 9, 2)), skip.hessian = TRUE, lower = c(6.19998713299522, 
    1e-04), upper = c(154.999678324881, 0.9999))

Coefficients:
      theta           m 
30.36971993  0.01814898 

Log-likelihood: -129.83 
> fitsad(mag5, "ls") ## Call without explicit arguments

Call:
mle2(minuslogl = LL, start = list(alpha = alfa), method = "Brent", 
    data = list(x = x), lower = 0, upper = upper)

Coefficients:
   alpha 
6.344334 

Log-likelihood: -132.08 
```

**Comment by andrechalom** [comment]
This is easy to implement for the non-truncated versions. But the truncated versions include a call to dtrunc(...), which will appear in the summary, as:

```R
bci <- bci[bci > 5]
> fitbs(bci, trunc=1)
Call:
mle2(minuslogl = function (N, S) 
-sum(dtrunc("bs", x = x, coef = list(N = N, S = S), trunc = trunc, 
    log = TRUE)), fixed = list(N = 21325L, S = 171L), data = list(
    x = c(92L, 23L, 156L, 27L, 983L, 22L, 28L, 27L, 236L, 21L, 
    52L, 201L, 39L, 294L, 188L, 55L, 23L, 100L, 54L, 87L, 19L, 
    264L, 25L, 39L, 38L, 85L, 25L, 22L, 13L, 63L, 325L, 364L, 
    55L, 98L, 12L, 47L, 88L, 13L, 16L, 33L, 285L, 21L, 26L, 18L, 
    81L, 12L, 55L, 177L, 1717L, 7L, 7L, 23L, 6L, 92L, 12L, 23L, 
    99L, 10L, 376L, 68L, 244L, 38L, 85L, 644L, 13L, 229L, 7L, 
    288L, 681L, 101L, 41L, 52L, 10L, 49L, 98L, 20L, 10L, 67L, 
    26L, 76L, 14L, 14L, 236L, 33L, 51L, 12L, 27L, 14L, 10L, 64L, 
    121L, 93L, 25L, 15L, 167L, 10L, 21L, 8L, 70L, 7L, 7L, 33L, 
    10L, 29L, 36L, 22L, 184L, 788L, 33L, 21L, 16L, 45L, 9L, 61L, 
    43L, 9L, 15L, 755L, 13L, 203L, 31L, 345L, 111L, 50L, 381L, 
    8L, 80L, 724L, 248L, 17L, 33L, 289L, 13L, 16L, 78L, 346L, 
    12L, 28L, 8L, 29L, 63L, 26L, 218L, 118L, 26L, 30L, 68L, 322L, 
    98L, 28L, 43L, 379L, 7L, 12L, 40L, 15L, 82L, 1681L, 147L, 
    32L, 58L, 163L, 617L, 25L, 164L, 12L, 143L, 149L, 67L, 45L, 
    10L)), eval.only = TRUE)
Coefficients:
    N     S 
21325   171 
Log-likelihood: -996.22 
```

Is this an acceptable summary?

**Comment by piklprado** [comment]
Sure a big improvement. 
And to get better: any way to abbreviate what follows "data" in the output?  For example to show the first 6 records followed by '...' ?

**Comment by piklprado** [comment]
I think the call for dtrunc is ok. But what are the "L"s after each number in some of the summaries?

**Comment by andrechalom** [comment]
The L after a number means that this is integer. Compare fitbs(bci) with fitbs(ARN82.eB.apr77).

Right now, we are using the "show" method from the mle2 class, which does some checking on the object, displays the call and some selected information. We can control what information is shown by passing different values to the mle2 function. There is no way to make the changes above by calling the mle2 function with different values - we would need to reimplement the "show" method for the fitsad and fitrad classes. Should we do that?

**Comment by piklprado** [comment]
Yes, more sensible show and summary methods for these classes was indeed a
plan.
Em 05/05/2015 13:38, "andrechalom" <notifications@github.com> escreveu:

**Comment by andrechalom** [comment]
OK, as this is an improvement over the original reported issue, I'm moving this to low priority.

**Comment by andrechalom** [comment]
Show method should also include a description of whether the distribution is 'C'ontinuous or 'D'iscrete, and sad or rad.
