### ISSUE TITLE
use hist instead of cut in octav and octavpred

### ISSUE THREAD

**Issue by piklprado** [piklprado/sads#14]
Rewrite octav and octavpred to use hist instead of cut, see example of dzsm and help page of cut: 
  ``Instead of ‘table(cut(x, br))’, ‘hist(x, br, plot = FALSE)’ is more efficient and less memory hungry.''

Also, more handy to choose midpoints and different cutting methods (e.g. rigth=TRUE or FALSE in cut)

**Comment by andrechalom** [comment]
The code using hist(x) really executes 5x faster than table(cut(x)):

```R
library(microbenchmark)
library(sads)
x <- 1+round(rexp(1e6, rate=5e-2)) # some test data
octav.orig <- function(x){ # Based on the original code, but without complicating parts
    oct <- 0:(ceiling(max(log2(x)))+1)
    N <- 2^(oct)
    oc.class <- cut(x, breaks=c(0, N), labels=oct)
    res <- as.data.frame(table(oc.class))
    res$upper <- N
    names(res)[1] <- "octave"
    res[,c(1,3,2)]
}
octav.hist <- function(x){ # Code modified to use hist instead of table(cut(x))
    oct <- 0:(ceiling(max(log2(x)))+1)
    N <- 2^(oct)
    res <- hist(x, breaks=c(0,N), plot=FALSE)
    data.frame(octave = oct, upper = res$breaks[-1], Freq = res$counts)
}
microbenchmark(octav.orig(x), octav.hist(x))
Unit: milliseconds
          expr       min        lq      mean    median        uq      max neval cld
 octav.orig(x) 342.32733 348.23013 373.13638 386.55440 389.92140 438.9457   100   b
 octav.hist(x)  82.75661  83.90155  90.67217  84.71552  85.92248 134.2046   100  a 
```

**Comment by andrechalom** [comment]
While working on this issue, I have noticed that the octav function generates an octav object in which the 'octave' column is a factor, but the 'upper' column is numeric. However, the octavpred methods generate an octav object in which both 'octave' and 'upper' are factors, which can lead to some very frustrating bugs - if anyone writes code that supposed that upper is or is not a factor. Which should be the data type of the upper column?

**Comment by piklprado** [comment]
If there's no obvious reason to make upper as a factor (for example some
method for the class octave), it seems more sensible to me making it numeric
Em 24/04/2015 21:31, "andrechalom" <notifications@github.com> escreveu:

**Comment by andrechalom** [comment]
I actually don't see any reason to use factors at all - except for data normalization, which is not the case here. So I'm pushing a pull request in which all columns are untransformed (so, int num num) for both octav and octavpred.
