### ISSUE TITLE
Coerce methods for classes octav and rad

### ISSUE THREAD

**Issue by piklprado** [piklprado/sads#22]
Create coerce methods for classes octav and rad. Maybe depends on integrity checks ( issue #6 )

**Comment by andrechalom** [comment]
Can you write an example of the usage of these classes? All the examples of an `as.rad` that I can think of can be replaced by `new("rad", ...)`, and the same for octav.

**Comment by piklprado** [comment]
I forgot. What occurs to me now is only as.octav to coerce a hist object to octav. Low priority, anyway
