### ISSUE TITLE
radpred lines for small samples

### ISSUE THREAD

**Issue by piklprado** [piklprado/sads#23]
The predicted line of rad plots seems irregular if the number of species is small:

```r
teste <- c(1,38,12,2,1,1,6,19,12,5,6,37,1,20,2,5,2,1,21)
teste.bs <- fitsad(teste, "bs")
teste.ls <- fitsad(teste, "ls")
plot(teste.bs, which=2)
plot(teste.ls, which=2)
```
![rplot002](https://cloud.githubusercontent.com/assets/6313365/4877734/de1200cc-62f4-11e4-9284-40a2273a0b43.png)
![rplot001](https://cloud.githubusercontent.com/assets/6313365/4877735/de180ad0-62f4-11e4-94a5-549ccca95c1c.png)

**Comment by andrechalom** [comment]
I'm not sure what is the issue here. The bottom plot is precisely the radpred of the broken-stick model - I believe the broken stick is simply a poor model for this data, which can be seen from the comparison of AICs with the ls fit:
```R
AICtab(teste.bs, teste.ls)
```
