### ISSUE TITLE
Which distributions can be used in rsad simulations?

### ISSUE THREAD

**Issue by andrechalom** [piklprado/sads#30]
I couldn't find in any of the reasonable places (man page, vignettes, even the function source code) an easy way to figure out for which sads we can run "rsad". Both "lnorm" and "geom" work, but logseries and broken stick do not:

```R
> rsad(S=100, frac=0.1, sad="bs")
```
> Error in do.call(sad, c(list(n = S), dots)) : 
>   could not find function "rbs"

```R
> rsad(S=100, frac=0.1, sad="ls")
```
> Error in do.call(sad, c(list(n = S), dots)) : 
>   could not find function "rls"

**Comment by piklprado** [comment]
The error meshed seems clear to me: there not r functions for some distributions. This is the case of most distributions implemented in sads such as geometric series and broken stick. We can eventually create these functions. But by now I think it's enough to warn in the help Rhys the argument 'sad' in 'rsads' only accepts distributions that have a 'r'  function. And to include an error statement in the function if this condition is not satisfied.

**Comment by piklprado** [comment]
Meshed=message. Damn automatic typing corrector

**Comment by andrechalom** [comment]
Still, I believe that this automatic conversion from sad='geom' to the function rgeom must be done after some error checking. I have encountered a similiar problem today with fitrad. This function accepts rad =c("gs", "mand", "rbs", "zipf"), but when I tried to fit a rad="ls", it worked - but not in the way expected:

```R
> object <- fitrad(x=ceiling(rexp(1e5, 1e-2)), rad="ls")
> class(object) 
[1] "fitsad"
```

**Comment by piklprado** [comment]
Sure, we need error checking in both cases.
Em 24/04/2015 21:45, "andrechalom" <notifications@github.com> escreveu:

**Comment by piklprado** [comment]
For fitarad and fitsad we need to allow only the available models as valid
choices of arguments sad and rad.
Em 24/04/2015 22:39, "Paulo Inácio Prado" <prado@ib.usp.br> escreveu:

**Comment by andrechalom** [comment]
Actually, fitrad and fitsad do not perform any type checking or conversion. They only delegate the call to the underlying fit<X> function. I'm fixing all of those problems using a ```match.arg()``` call inside the top-level functions.
