### ISSUE TITLE
Replace bisection in [q] functions

### ISSUE THREAD

**Issue by andrechalom** [piklprado/sads#35]
The method used to find quantiles for discrete probability functions (qbs, qls, qpoilog, qpower, plus qpoix and qpoig) in the current release is the search by bisection. This method has three issues:
- A lot of duplicated code is found on this functions
- The method is generally inefficient, as it converges linearly (other methods may converge quadratically)
- The current implementation hangs if the p is very close to 1:
```R
> qpoilog(0.9999999, 1,1) ## HANGS
```

Maybe this code can be substituted by uniroot calls?

**Comment by andrechalom** [comment]
Update:

- The code in use actually does not perform bisection as I inferred, but sequential comparisons, which is **very** inefficient.
- Bisection code is rather efficient in this case, as the results are constrained to be integers. Other techniques are more difficult to implement in this case.
- The problem with qpoilog(0.99999...) is a problem with ppoilog, actually, as ppoilog(X, ...) never exceeds 0.9999996. I'm including a check for non-convergence.
- Code duplication remains an issue.

**Comment by andrechalom** [comment]
A small comparison of the new qpoilog _versus_ the original qpoilog.orig performances:

```R
> p <- 0:20/20
> qpoilog(p, 1, 1)
 [1]   0   0   0   0   1   1   1   2   2   2   3   3   4   4   5   6   7   8  10  15 Inf
> microbenchmark(qpoilog(p, 1, 1), qpoilog.orig(p, 1, 1))
Unit: milliseconds
                  expr       min        lq      mean    median        uq       max neval cld
      qpoilog(p, 1, 1)  6.328103  6.454206  6.642205  6.575216  6.661761  7.869904   100  a 
 qpoilog.orig(p, 1, 1) 36.764368 58.563975 66.690892 66.372270 75.559158 96.157810   100   b
```

**Comment by andrechalom** [comment]
Working example on https://github.com/andrechalom/sads/tree/Fix35, but depends on solving issue #8 for some of the other distributions.

**Comment by piklprado** [comment]
Now issue #8 is solved is there any open issue here?
