### ISSUE TITLE
Poisson-gamma and Poisson-exponential

### ISSUE THREAD

**Issue by piklprado** [piklprado/sads#4]
Finish functions for distribution and fitting fo Poisson-gamma and Poisson-exponential. Currently only density functions (old code, check) available.

**Comment by andrechalom** [comment]
[dpq] functions and fitsad functions implemented in https://github.com/andrechalom/sads/tree/Fix4

Still need to check the starting values for the fitting before merging.

**Comment by andrechalom** [comment]
qpoix is not converging, we probably need to fix #35 before merging.

**Comment by piklprado** [comment]
Note that Poisson-exponential is McArthur's Broken-stick:

http://www1.maths.leeds.ac.uk/~sta6ajb/drep0010.pdf

**Comment by piklprado** [comment]
Fitting with `frac` as a free parameter is very problematic.

**Comment by andrechalom** [comment]
Okay.

Again, I need more specific instructions on what to do here. Should we keep [dpq]poix as an independent distribution, or should we make these functions call [dpq]bs under the hood? Should fitpoix exist? Should it accept "frac" as a mandatory argument?

What about [dpq]gamma? I read in some places that it was equivalent to a negative binomial, so the same questions apply.

**Comment by piklprado** [comment]
By now we can keep [dpq] functions and remove the fitting functions. Also we should include relevant informations dicussed here in man pages.
