### ISSUE TITLE
Transform plotprofmle in S4 method?

### ISSUE THREAD

**Issue by andrechalom** [piklprado/sads#56]
Should we transform plotprofmle in an S4 method? 

That would allow us to define a method for fitsad/fitrad that calculates the profile and draws the plot, instead of throwing back a "not a profile or profile.mle2 object" error.

I suggest the plotprofmle method applied on a fitsad/fitrad object should "cat" the following:
"NOTICE: calculating the profile for this fitted object. You should consider storing the profile in a new variable and calling plotprofmle on the resulting object."

**Comment by piklprado** [comment]
I agree.
