### ISSUE TITLE
Error using '...' in fitweibull

### ISSUE THREAD

**Issue by MarioJose** [piklprado/sads#60]
Error happens when I use **"..."** to inform other parameter to `fitweibull` (that will be used in `optmin`). 

```r
set.seed(42)
dt <- rweibull(100, shape = 0.8, scale = 2)
fitweibull(dt, start.value = c(shape=0.7, scale=1.8), control=list(parscale=c(shape=0.79, scale=1.99)))
Error in call$control$parscale : $ operator is invalid for atomic vectors
```

`optmin` search for a list named **control** to access **parscale** and parameters defined at **parscale**. To access this, `optmin` use `$`. When the following call is used in `fitweibull`:

```r
result <- do.call("mle2", c(list(LL, start = list(shape = ka,  scale = theta), data = list(x = x)), ...))
```

the function `c` convert **control** in **numeric** and then `optmin` can't access **parscale** with `$`. Function return this error:

```r
Error in call$control$parscale : $ operator is invalid for atomic vectors
```

Instead of use `c` you can use `list`. With this, **control** will be a **list** inside **"..."** and `optmin` can use `$` to access **parscale** and parameters at **parscale**.

```r
result <- do.call("mle2", list(LL, start = list(shape = ka,  scale = theta), data = list(x = x), ...))
```

Other option is to use **dots** variable instead **"..."** at the first call:

```r
result <- do.call("mle2", c(list(LL, start = list(shape = ka,  scale = theta), data = list(x = x)), dots))
```

With this, **control** will be a **list**.

**Comment by andrechalom** [comment]
You're absolutely right. That is exactly the reason why the "dots" variable is created in the first line of these functions. I will fix this and submit a new version as soon as possible.

**Comment by andrechalom** [comment]
Fixes for these two issues have been submitted here on github, we will release a new version on CRAN asap.
