### ISSUE TITLE
Dots on AICc

### ISSUE THREAD

**Issue by MarioJose** [piklprado/sads#66]
Dears, AICc manual inform that this method compute auxiliary information, but when I inform other parameter (base, logLik. delta, weights) to show on table occur a error:
```r
data(moths)
modls <- fitls(moths)
modln <- fitlnorm(moths)
AICc(modls, modln, weights=TRUE)
```

```
Error in AICc(modls, modln, nobs = length(moths), base = TRUE) : 
  all objects in list must be class mle2 or inherit from mle2
```
In source of method, dots are models and parameter concatenated:

```r
L <- list(object, ...)
```

Then, when check `L` occur the error:

```r
if (!all(sapply(L, function(x) inherits(x, "mle2")))) 
    stop("all objects in list must be class mle2 or inherit from mle2")
```

It is better to inform on manual if dots can be used to set parameter or only models.

Best regards,

Mario

**Comment by andrechalom** [comment]
Actually, I believe the "weights" and other such parameters should be
passed to a `ICtab` function (`AICtab`, `AICctab`, etc), instead of to the
`AIC` or `AICc` functions:
```R

> modls <- fitls(moths)
> modln <- fitlnorm(moths)
> AICctab(modls, modln, weights=TRUE)
      dAICc df weight
modls  0.0  1  1
modln 22.1  2  <0.001
```

However, the `AICc` is failing for other reasons when called with more
than one argument:

```R

> AICc(modls, modln)
Error in nobs.default(X[[i]], ...) : no 'nobs' method is available
>

```

**Comment by andrechalom** [comment]
Actually, I believe the "weights" and other such parameters should be
passed to a `ICtab` function (`AICtab`, `AICctab`, etc), instead of to the
`AIC` or `AICc` functions:
```R
> modls <- fitls(moths)
> modln <- fitlnorm(moths)
> AICctab(modls, modln, weights=TRUE)
      dAICc df weight
modls  0.0  1  1
modln 22.1  2  <0.001
```

However, the `AICc` is failing for other reasons when called with more
than one argument:

```R
> AICc(modls, modln)
Error in nobs.default(X[[i]], ...) : no 'nobs' method is available
>
```

**Comment by MarioJose** [comment]
The saw too that AICc computed value are a bit different in `AICctab` and `AICc`

```r
modls <- fitls(moths)
modln <- fitlnorm(moths)
AICctab(modls, modln, base=TRUE)
      AICc   dAICc  df
modls 2177.4    0.0 1 
modln 2199.5   22.1 2 

AICc(modls, modln, nobs = length(moths))
      AICc df
1 2175.442  1
2 2195.496  2
```

The difference is **2** multiplying `df`. On bbmle, AICc method use

`-2 * c(object) + k*df+2*df*(df+1)/(nobs-df-1)` 

and on sads

`-2*unlist(logLiks)+k*df*(df+1)/(nobs-df-1)`

**Comment by andrechalom** [comment]
@MarioJose, we have submitted today a new version (sads-0.2.2) to CRAN, it will be available in a couple of days. Please install it to use the corrected version of the functions.

**Comment by MarioJose** [comment]
Ok, thank you!
p.s.: @andrechalom, the current CRAN version (2015-07-12) is 0.2.2. I've it installed. New version will be 0.2.3?

**Comment by andrechalom** [comment]
Sorry, the new version is 0.2.3, will be up soon!

**Comment by andrechalom** [comment]
On CRAN now!
