### ISSUE TITLE
Improve start values in fitmand

### ISSUE THREAD

**Issue by piklprado** [piklprado/sads#9]
Evaluate if Mouillot & Lepretre's (2000, Environmental monitoring and assessment) method for fitting Zipf-Mandelbrot is useful to find starting values for fitmand.

**Comment by andrechalom** [comment]
The method is pretty straightforward, however it depends on an arbitraty decision of what is the "right-hand side" of the graph. I've implemented it using the 75% less abundant species, code here:

```R
rad.tab <- rad(bci)
x75 <- rad.tab[(floor(dim(rad.tab)[1]/4)):dim(rad.tab)[1],]
x75 <- x75[x75$abund > 1, ] # excludes singletons
shat <- - coef(lm(log(abund)~log(rank), data=x75))[2]
```
I've tried fitting the same data, with or excluding singletons. For comparison, the fitted values for the fitmand and the initial guess for our data sets:

Data | Fitted exponent | Guess w singles | Guess w/o singles
------ | -------------------- | --------- | -----
birds | 3.948 | 3.468 | 3.214
moths | 1.682 | 3.078 | 2.520
bci | 2.006 | 3.259 | 2.742
okland | 16.254 | 2.786 | 2.786
 
As you can see, the method does not seem to provide a marked improvement over a fixed value of "2". I've tried other values for cutting the data, to the same results. Submitting it anyway, as it is not expensive to calculate.
